### PR TITLE
atm integration work

### PR DESCRIPTION
**Pull request by flexfinRTP**
keep open till mint success

### CODE REVIEW

**Comment by Lenoftawa** [comment]
This overwrites PR a bug fix in the contract.  But it's actually a problem in my branch too.  We can live with it as I will commit a new change soon anyway.

**Comment by flexfinRTP** [comment]
in this commit, [f468806, I have double-checked the latest commit from your contract is updated. should have latest now

**Comment by flexfinRTP** [comment]
added readme steps for ui easy setup

**Comment by flexfinRTP** [comment]
fixed conflicts, ready for merge so others can test.

**Pull request merged**
